### ISSUE TITLE
Constructors, getters and setters

### ISSUE THREAD

**Issue by TomOrth** [techguy9984/TBA-API#7]
Your code lacks the above, and it is considered good practice to use them

**Comment by widavies** [comment]
Use the ATBA class as opposed to the TBA class for constructors. I know
it's good practice to use constructors, but there are advantages and
disadvantages to each. You can read more on the wiki page. I will add
getters and setters as well within the next couple days, but for now just
use the class.var format for getting and setting values.

Thanks,
Will

**Comment by TomOrth** [comment]
But what about the models? They too lack constructors

**Comment by widavies** [comment]
Yeah I suppose I can add constructors to them. I didn't really see it as a
big deal because users don't create model classes, just pull information
from them. Plus the way that the TBA servers return data, I have to have
code that catches exceptions for every json variable hash request so
hash.get ("name"); could fail so constructors aren't as good because if one
variable fails then the whole thing will fail.

**Comment by TomOrth** [comment]
Fair enough

**Comment by widavies** [comment]
In any case, I can still add them if that would help you to understand /
use the api better. As well as other users.

**Comment by TomOrth** [comment]
I get how your api works.  I just thought constructors would be useful but your explanation of why it lacks them is valid

**Comment by widavies** [comment]
Sounds good, thanks for the input. Hope you find the api useful
